# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit autoupdate
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version
  rev: v0.6.3
  hooks:
    # Run the linter
    - id: ruff
    # Run the formatter
    - id: ruff-format
      args: [ --check ]
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.379
  hooks:
  - id: pyright
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    # Checks for files that contain merge conflict strings
    - id: check-merge-conflict
    # Attempts to load all TOML files to verify syntax
    - id: check-toml
    # Trims trailing whitespace
    - id: trailing-whitespace
    # Makes sure files end in a newline and only a newline
    - id: end-of-file-fixer
