minio_bucket: data

my_name: Игра Жигули | Ведущий

help_comand_hint: Получить помощь

error_message: |-
  😔 Произошла ошибка... Гейм-мастерам уже сообщено о ней!

chats:
  admin: -4503274152
  bank:  -4565219940
  fight: -4515153421
  teams:
    - name: Команда 1
      chat_id: -4560700860
      map_color: "#90ee90"
      color_emoji: 🟢
      default_district_name: Райончик 1
    - name: Команда 2
      chat_id: -4557531976
      map_color: "#4169e1"
      color_emoji: 🔵
      default_district_name: Райончик 2
    - name: Команда 3
      chat_id: -4539193293
      map_color: "#f0e68c"
      color_emoji: 🟡
      default_district_name: Райончик 3
    - name: Команда 4
      chat_id: -4535779028
      map_color: "#9400d3"
      color_emoji: 🟣
      default_district_name: Райончик 4
    - name: Команда 5
      chat_id: -4534317546
      map_color: "#dc143c"
      color_emoji: 🔴
      default_district_name: Райончик 5
    - name: Команда 6
      chat_id: -4530246486
      map_color: "#ff8c00"
      color_emoji: 🟠
      default_district_name: Райончик 6

districts_map:
  backing_filename: backing.png
  text_filename: text.png
  none_map_color: "#dcdcdc"
  default_districts:
    - name: Райончик 1
      mask_filename: mask_01.png
    - name: Райончик 2
      mask_filename: mask_02.png
    - name: Райончик 3
      mask_filename: mask_03.png
    - name: Райончик 4
      mask_filename: mask_04.png
    - name: Райончик 5
      mask_filename: mask_05.png
    - name: Райончик 6
      mask_filename: mask_06.png
    - name: Райончик 7
      mask_filename: mask_07.png
    - name: Райончик 8
      mask_filename: mask_08.png
    - name: Райончик 9
      mask_filename: mask_09.png
    - name: Райончик 10
      mask_filename: mask_10.png
    - name: Райончик 11
      mask_filename: mask_11.png
    - name: Райончик 12
      mask_filename: mask_12.png
    - name: Райончик 13
      mask_filename: mask_13.png
    - name: Райончик 14
      mask_filename: mask_14.png
    - name: Райончик 15
      mask_filename: mask_15.png
    - name: Райончик 16
      mask_filename: mask_16.png
    - name: Райончик 17
      mask_filename: mask_17.png
    - name: Райончик 18
      mask_filename: mask_18.png

help_messages:
  admin:
    key: Получить помощь
    message: |-
      Это чат *⚙️ администрирования* игры Жигули 2024

      Выберете на клавиатуре кнопку `🗺️ Райончики` чтобы увидеть текущую карту с отметками о захвате

      Выберете на клавиатуре кнопку `⚔️ Стрелка` чтобы увидеть команды, которые вызваны на бой в данный момент

      Сюда также будут приходить ошибки работы бота 🚨
    keyboard:
      - show_districts_map

  bank:
    key: Получить помощь
    message: |-
      Это чат станции *🏦 Банк* игры Жигули 2024

      Выберете на клавиауре кнопку `💰 Начать продажу райончика`
    keyboard:
      - show_districts_map
      - district_sell_start_choose_team

  fight:
    key: Получить помощь
    message: |-
      Это чат станции *🤼 Стрелка* игры Жигули 2024

      Выберете на клавиатуре `⚔️ Начать стрелку за райончик`
    keyboard:
      - show_districts_map
      - district_fight_start_choose_assaulter

  team:
    key: Получить помощь
    message: |-
      Добро пожаловать в игру *🪆 Жигули!*

      🤖 Я - бот-ведущий, который поможет вам держать ваши райончики 👊

      Вы *{{ context.team.color_emoji }} {{ context.team.name }}*

      Нажмите на кнопку `🗺️ Райончики` чтобы узнать кто на каком райончике
      _Я буду уведомплять когда вы или другие команды будут покупать райончики_

      🤼 Если вас вызовут на стрелку - я вышлю уведомление!
      _📢 Лучше держать этот чат со включёнными уведомлениями_

      Если вам нужна помощь с механиками игры, нажмите на кнопку `🔩 Механики игры`

      *И помните, вы все - пацаны с улицы - а кругом враги! Удачи!*
    keyboard:
      - show_districts_map
      - game_mechanics

keyboard:
  cancel:
    key: 🚫 Отмена
    message: Все операции отменены...

  game_mechanics:
    key: 🔩 Механики игры
    messages:
      - |-
        *Краткие условия игры*
          — Зарабатывайте деньги *на станциях 🎪*
          — Покупайте новые райончики *в Банке 🏦*
          — Выигрывайте новые райончики, вызывая вражескую команду *на стрелку 🤼*
          — Покупайте шмот и жвачку *на базарчике 🛍️*
      - |-
        *Как выкупить райончик?*
          — Приходите в *🏦 Банк* с котлетой 💵
          — Выбирайте свободный райончик
          — Оформляйте покупку через *👩🏻‍💼 Кассиршу*
      - |-
        *Как выиграть райончик на стрелке?*
          — Приходите на станцию *🤼 Стрелка* (не менее 8 человек от команды❗)
          — Выберите, чей райончик хотите выиграть и передайте эти слова *🦅 Братку* и заплатите стартовый взнос
          — Немного подождите вражескую команду — можете поиграть на станции рядышком
          — Сражайтесь за райончик в честном бою!
    keyboard:
      - show_districts_map
      - game_mechanics

  show_districts_map:
    key: 🗺️ Райончики
    message: |-
      *🗺️ Карта контроля над райончиками*:

      {% if context.team -%}
      *Вы {{ context.team.color_emoji }} {{ context.team.name }}* - {{ context.team.district_num }} {% if context.team.district_num == 1 %}райончик{% elif context.team.district_num <= 3 %}райончика{% else %}райончиков{% endif %} под контролем
      {% endif %}

      {%- for team in context.teams %}
      {{ team.color_emoji }} {{ team.name }} - {{ team.district_num }} {% if team.district_num == 1 %}райончик{% elif team.district_num <= 3 %}райончика{% else %}райончиков{% endif %} под контролем
      {% endfor %}
      ⚪ Ничейная территория

  district_sell_start_choose_team:
    key: 💰 Начать продажу райончика
    message: |-
      💰 Начата продажа райончика

      👥 Выберете команду, которая осуществляет покупку

  district_sell_choose_district:
    key: Выбрите райончик для покупки
    message: |-
      🗾 Выберете райончик для продажи

      _⌨️ На клавиатуре ниже приведены только доступные к покупке райончики_

  district_sell_confirm:
    key: Подтвердлите покупку
    message: |-
      📝 Подтвердите покупку

      *{{ context.team_name }} покупакет {{ context.district_name }}*
    keyboard:
      - district_sell_confirmed
      - cancel

  district_sell_confirmed:
    key: ✅ Подтвердить покупку
    message: |-
      ✅ Покупка подтверждена

      *{{ context.team_name }} покупакет {{ context.district_name }}*
    keyboard:
      - show_districts_map
      - district_sell_start_choose_team

  district_sell_notification_all:
    key: Уведомление о состоявшейся покупке райончика
    message: |-
      ⚠️ {{ context.team_name }} покупакет {{ context.district_name }}

      _Успевайте выкупить оставшиеся райончики!_

  district_sell_notification_owner:
    key: Уведомление о состоявшейся покупке райончика для покупателей
    message: |-
      ✅ Ваша команда покупакет {{ context.district_name }}

  district_fight_start_choose_assaulter:
    key: ⚔️ Начать сражение за райончик
    message: |-
      ⚔️ Начато сражение за райончик

      👥 Выберете команду, которая нападает на райончик
      _Это та команда, которая пришла первая_

  district_fight_choose_defender:
    key: Выберите защищающегося
    message: |-
      🛡️ Выберете защищающуюся команду
      _Команда, которая будет вызывана на бой_

  district_fight_notify_defender:
    key: 🛡️ Вызвать защищающуюся команду
    message: |-
      *🔥🛡️🔥 {{ context.defender_team_name }} вызвана на стрелку*

  district_fight_notification_defender:
    key: Уведомление для защищающейся команды
    message: |-
      *🔥🛡️🔥 {{ context.assaulter_team_name }} вызывает вас на стрелку!*
      _Скорее приходите на станцию_ *🤼 Стрелка*

  district_fight_result:
    key: Выберете кто победил в сражении
    message: |-
      🔥🗡️🛡️ Выберете кто победил в сражении

      *{{ context.assaulter_team_name }} нападает на {{ context.defender_team_name }}*

      _⌨️ Если защищающаяся_ *{{ context.defender_team_name }}* _ещё не пришла, ей можно выслать повторное уведомление при помощи клавиатуры ниже_

  district_fight_choose_district:
    key: Выберите райончик, которая отожмёт победитель у проигравшего
    message: |-
      🗾 Выберите райончик, который отожмёт *{{ context.winner_team_name }}* у *{{ context.loser_team_name }}*

      _⌨️ На клавиатуре ниже приведены только те райончики, которые принадлежат_ *{{ context.loser_team_name }}*

  district_fight_done:
    key: Отжат райончик
    message: |-
      🚩 Бой закончен, райончик отжат

      *{{ context.winner_team_name }} отжимает {{ context.district_name }} у {{ context.loser_team_name }}*
    keyboard:
      - show_districts_map
      - district_fight_start_choose_assaulter

  district_fight_notification_all:
    key: Уведомление о том, что райончик был отжат
    message: |-
      ⚠️ {{ context.winner_team_name }} отжимает {{ context.district_name }} у {{ context.loser_team_name }}

      _Успевайте отжать оставшиеся райончики!_

  district_fight_notification_winner:
    key: Уведомление о том, что райончик был отжат для победителя
    message: |-
      ✅ Ваша команда отжимает {{ context.district_name }} у {{ context.loser_team_name }}

  district_fight_notification_loser:
    key: Уведомление о том, что райончик был отжат для проигравшего
    message: |-
      ❌ Ваша команда теряет {{ context.district_name }}, который отжала {{ context.winner_team_name }}
